print("Git Course first")
print("Hello World")
print(2)
print("Hello World2")
print("UpdatedBranch")

print("Mering UpdatedBranch to main branch")
print("Add")
print("Final Commit")
print("bugmix")
print('merging bugmix to main')
print('git main branch')